### ISSUE TITLE
ios-arm64_armv7 build is missing from 2.12.0 xcframework

### ISSUE THREAD

**Issue by kinwahlai** [abbiio/spm#1]
ios-arm64_armv7 build is missing from 2.12.0 xcframework
![Screen Shot 2021-11-12 at 8 18 42 AM](https://user-images.githubusercontent.com/1986672/141434122-b232ab33-fb07-4f06-9283-960d28771b89.png)

Error in the build log
`When building for iOS, the expected library /Users/dlai/Library/Developer/Xcode/DerivedData/ww-adfywpgpgyvwzoecicdpxgcdtzyl/SourcePackages/checkouts/spm/WalkMeSDK.xcframework/ios-arm64_armv7/WalkMeSDK.framework was not found in /Users/dlai/Library/Developer/Xcode/DerivedData/ww-adfywpgpgyvwzoecicdpxgcdtzyl/SourcePackages/checkouts/spm/WalkMeSDK.xcframework
`

**Comment by classic-chris** [comment]
I'm experiencing the same issue. I have also tried manually installing from the CDN using the newest version of the xcframework (2.12.2). This release _does_ have ARM64 and i386 versions packages but still fails to build on my Apple silicon device with the following error:

<img width="574" alt="Screenshot 2021-11-12 at 10 05 25" src="https://user-images.githubusercontent.com/22204232/141452587-08af6708-4965-481f-8238-625fca48fb38.png">
